GET http://localhost:3001/

###

GET http://localhost:3001/twitter/user/15/

###

POST http://localhost:3001/user/register/
Content-Type: application/json

{
    "username" : "rahul_2021",
    "password" : "rahul123",
    "name" : "Rahul",
    "gender" : "male"
}

###

PUT http://localhost:3001/user/update/15/
Content-Type: application/json

{
    "username" : "rahul_2021",
    "password" : "rahul123",
    "name" : "Rahul Attuluri",
    "gender" : "male"
}

###

DELETE http://localhost:3001/user/delete/17/


//API - 1
#### 
POST http://localhost:3001/register/
Content-Type: application/json

{
 "username" : "stephen_st",
 "password" : "stephen123",
 "name" : "Stephen Morah",
 "gender" : "male"
}

//API - 2
###
POST http://localhost:3001/login/
Content-Type: application/json

{
 "username" : "stephen_st",
 "password" : "stephen123",
 "name" : "Stephen Morah",
 "gender" : "male"
}

//jwtwebtoken for stephen 
//{"jwtToken":"eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InN0ZXBoZW5fc3QiLCJ1c2VySWQiOjE0LCJpYXQiOjE2ODYwMjk5Nzd9.G5mecChzcWHEp94j2lBsbwO_4RXjF5JTSGh9NmXKEN8"}

//API - 3
### 
GET http://localhost:3001/user/tweets/feed/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InN0ZXBoZW5fc3QiLCJ1c2VySWQiOjE0LCJpYXQiOjE2ODYwMjk5Nzd9.G5mecChzcWHEp94j2lBsbwO_4RXjF5JTSGh9NmXKEN8

//API - 4
###
GET http://localhost:3001/user/following/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InN0ZXBoZW5fc3QiLCJ1c2VySWQiOjE0LCJpYXQiOjE2ODYwMjk5Nzd9.G5mecChzcWHEp94j2lBsbwO_4RXjF5JTSGh9NmXKEN8

//API - 5
###
GET http://localhost:3001/user/followers/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InN0ZXBoZW5fc3QiLCJ1c2VySWQiOjE0LCJpYXQiOjE2ODYwMjk5Nzd9.G5mecChzcWHEp94j2lBsbwO_4RXjF5JTSGh9NmXKEN8

//API - 6
###
GET http://localhost:3001/tweets/1/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InN0ZXBoZW5fc3QiLCJ1c2VySWQiOjE0LCJpYXQiOjE2ODYwMjk5Nzd9.G5mecChzcWHEp94j2lBsbwO_4RXjF5JTSGh9NmXKEN8

//API - 7
###
GET http://localhost:3001/tweets/4/likes/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InN0ZXBoZW5fc3QiLCJ1c2VySWQiOjE0LCJpYXQiOjE2ODYwMjk5Nzd9.G5mecChzcWHEp94j2lBsbwO_4RXjF5JTSGh9NmXKEN8

//API - 8
###
GET http://localhost:3001/tweets/7/replies/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InN0ZXBoZW5fc3QiLCJ1c2VySWQiOjE0LCJpYXQiOjE2ODYwMjk5Nzd9.G5mecChzcWHEp94j2lBsbwO_4RXjF5JTSGh9NmXKEN8

//API - 9
###
GET http://localhost:3001/user/tweets/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InN0ZXBoZW5fc3QiLCJ1c2VySWQiOjE0LCJpYXQiOjE2ODYwMjk5Nzd9.G5mecChzcWHEp94j2lBsbwO_4RXjF5JTSGh9NmXKEN8

//API - 10
###
POST http://localhost:3001/user/tweets/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InN0ZXBoZW5fc3QiLCJ1c2VySWQiOjE0LCJpYXQiOjE2ODYwMjk5Nzd9.G5mecChzcWHEp94j2lBsbwO_4RXjF5JTSGh9NmXKEN8
Content-Type: application/json

{
   "tweet": "The Mornings..."
}

//API - 11
###
DELETE http://localhost:3001/tweets/13/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InN0ZXBoZW5fc3QiLCJ1c2VySWQiOjE0LCJpYXQiOjE2ODYwMjk5Nzd9.G5mecChzcWHEp94j2lBsbwO_4RXjF5JTSGh9NmXKEN8

