GET http://localhost:3001/

###

GET http://localhost:3001/twitter/user/16/

###

POST http://localhost:3001/user/register/
Content-Type: application/json

{
    "username" : "gokul_2021",
    "password" : "gokul123",
    "name" : "GokulKrishna",
    "gender" : "male"
}

###

PUT http://localhost:3001/user/update/15/
Content-Type: application/json

{
    "username" : "rahul_2021",
    "password" : "rahul123456",
    "name" : "Rahul Attuluri",
    "gender" : "male"
}

###

DELETE http://localhost:3001/user/delete/19/
